using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace turnero_medico_backend.Migrations
{
    /// <inheritdoc />
    public partial class CreateSecretariasTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Crear la tabla solo si no existe (la migración anterior pudo haber fallado parcialmente)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Secretarias"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Nombre"" text NOT NULL,
                    ""Apellido"" text NOT NULL,
                    ""Dni"" text NOT NULL,
                    ""Email"" text NOT NULL,
                    ""Telefono"" text NOT NULL,
                    ""UserId"" text NULL,
                    CONSTRAINT ""PK_Secretarias"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Secretarias_AspNetUsers_UserId"" FOREIGN KEY (""UserId"")
                        REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Secretarias_Dni""
                ON ""Secretarias"" (""Dni"");
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Secretarias_UserId""
                ON ""Secretarias"" (""UserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "Secretarias");
        }
    }
}
